### ISSUE TITLE
Issues with special characters (emojis maybe?)

### ISSUE THREAD

**Issue by frzsombor** [Stichoza/google-translate-php#69]
Looking at my error log, I just found that if a special character (in my error log: 💘 - [more info](http://unicode-table.com/en/1F498/) ) was entered in a sentence, something went wrong, and the folloing exception was raised:

```
'Client error: `POST http://translate.google.com/translate_a/single` resulted in a `403 Forbidden` response: <!DOCTYPE html> <html lang=en>   <meta charset=utf-8>   <meta name=viewport content="initial-scale=1, minimum-scale=1, w (truncated...) ' 
in /path/to/vendor/stichoza/google-translate-php/src/Stichoza/GoogleTranslate/TranslateClient.php:286 
Stack trace: 
#0 /path/to/vendor/stichoza/google-translate-php/src/Stichoza/GoogleTranslate/TranslateClient.php(323): Stichoza\GoogleTranslate\TranslateClient->getResponse('TEST \xF0\x9F\x92\x98') 
#1 /path/to/vendor/stichoza/google-translate-php/src/Stichoza/GoogleTranslate/TranslateClient.php(185): Stichoza\GoogleTranslate\TranslateClient->instanceTranslate('TEST \xF0\x9F\x92\x98') 
#2 /path/to/include/googletranslate.class.php(61): Stichoza\GoogleTranslate\TranslateClient->__call('translate', Array) 
#3 /path/to/include/googletranslate.class.php(61): Stichoza\GoogleTranslate\TranslateClient->translate('TEST \xF0\x9F\x92\x98') 
#4 /path/to/index.php(24): GoogleTranslate->getCode() 
#5 {main} [] []
```

Of course Google Translate [translates](https://translate.google.hu/#auto/en/TEST%20%F0%9F%92%98) it, so for me, it looks like a bug in this project.

**Comment by frzsombor** [comment]
Sorry, I didn't notice this is a duplicate of #42
