### ISSUE TITLE
Uncaught ErrorException: cURL error 60

### ISSUE THREAD

**Issue by LeeThompson** [Stichoza/google-translate-php#91]
```
PHP Fatal error:  Uncaught ErrorException: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) in D:\PHP\vendor\stichoza\google-translate-php\src\Stichoza\GoogleTranslate\TranslateClient.php:324
Stack trace:
#0 D:\PHP\vendor\stichoza\google-translate-php\src\Stichoza\GoogleTranslate\TranslateClient.php(361): Stichoza\GoogleTranslate\TranslateClient->getResponse('Parties carr\xE9es...')
#1 D:\PHP\vendor\stichoza\google-translate-php\src\Stichoza\GoogleTranslate\TranslateClient.php(185): Stichoza\GoogleTranslate\TranslateClient->instanceTranslate('Parties carr\xE9es...')
#2 D:\Source\_nnplus\translate_titles\test.php(12): Stichoza\GoogleTranslate\TranslateClient->__call('translate', Array)
#3 {main}
  thrown in D:\PHP\vendor\stichoza\google-translate-php\src\Stichoza\GoogleTranslate\TranslateClient.php on line 324

```
`PHP 7.1.7 (cli) (built: Jul  6 2017 16:51:33) ( NTS MSVC14 (Visual C++ 2015) x64 )`

**Comment by LeeThompson** [comment]
Working around it with:

`$tr->setHttpOption(['verify' => false]);`

**Comment by mbelatar** [comment]
Call to undefined method Stichoza\GoogleTranslate\GoogleTranslate::setHttpOption()

**Comment by SamHeijder2002** [comment]
> Call to undefined method Stichoza\GoogleTranslate\GoogleTranslate::setHttpOption()

i have the same problem

**Comment by d76g** [comment]
I just installed the repo and faced this problem using Laravel 9. @Stichoza , any updates about the solution ?
